# lightning.pytorch==2.0.9.post0
seed_everything: 42
trainer:
  accelerator: gpu
  strategy: ddp_find_unused_parameters_true
  devices: [0,1]
  num_nodes: 1
  precision: 32
  logger:
    - class_path: CSVLogger
      init_args:
        save_dir: logs
        name: experiment

  callbacks:
    - class_path: lightning.pytorch.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 1
        leave: true
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        every_n_epochs: 10
        save_on_train_epoch_end: True
        save_top_k: -1
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step

  max_epochs: 50
  check_val_every_n_epoch: 10
  num_sanity_val_steps: 0
  log_every_n_steps: 1
  deterministic: True
  inference_mode: True
  use_distributed_sampler: false   # ★ 公平：test/val 不复用样本
  sync_batchnorm: True

model:
  lr_g: 0.00016
  lr_d: 0.0001
  disc_grad_penalty_freq: 10
  disc_grad_penalty_weight: 0.5
  lambda_rec_loss: 0.5
  optim_betas: [0.5, 0.9]
  eval_mask: False
  eval_subject: True

  diffusion_params:
    n_steps: 10
    beta_start: 0.1
    beta_end: 3.0
    gamma: 1
    n_recursions: 2
    consistency_threshold: 0.0   # ★ 公平：都走满 K

  generator_params:
    self_recursion: True
    image_size: ${data.image_size}
    z_emb_dim: 256
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16]
    dropout: 0.0
    resamp_with_conv: True
    conditional: True
    fir: True
    fir_kernel: [1, 3, 3, 1]
    skip_rescale: True
    resblock_type: biggan
    progressive: none
    progressive_input: residual
    embedding_type: positional
    combine_method: sum
    fourier_scale: 16
    nf: 64
    num_channels: 2
    nz: 100
    n_mlp: 3
    centered: True
    not_use_tanh: False

  discriminator_params:
    nc: 2
    ngf: 32
    t_emb_dim: 256

data:
  train_batch_size: 4
  val_batch_size: 4
  test_batch_size: 64

  dataset_dir: /home/xiaobin/Projects/SelfRDB/dataset/brats256_selfrdb_official
  source_modality: t1          # ★ 注意大小写要和数据文件夹一致
  target_modality: t2
  dataset_class: NumpyDataset
  image_size: 256
  padding: True
  norm: True
  num_workers: 32
  # --- Subset controls ---
  # 验证集：只评 N 个样本（0 表示全量）
  val_max_samples: 200
  val_subset_mode: random   # first | random
  val_subset_seed: 42
  # 测试集：只评 N 个样本（0 表示全量）
  test_max_samples: 200
  test_subset_mode: random  # first | random
  test_subset_seed: 42

ckpt_path: 
# /home/xiaobin/Projects/SelfRDB/logs/download/brats_t1_t2.ckpt
